export const MAX_SKILLS = 5;
export const MAX_HOBBIES = 5;
export const MAX_HOBBY_LENGTH = 20;
export const JWT_EXPIRY = 60 * 60 * 24; // 24 hours
export const CONNECTIONS_PER_PAGE = 6;
export const INITIAL_PROFILES_PER_PAGE_FEED = 5;
export const PROFILES_PER_PAGE_FEED = 15;
export const FEED_PREFETCH_THRESHOLD = 1;
export const MAX_BIO_LENGTH = 200;
export const MAX_WEBSITE_LENGTH = 100;
